### PR TITLE
Setup and add leaderboard layout

### PR DESCRIPTION
**Pull request by olawalecoder**
At this stage, I have done the following.
- Setup Webpack
-Added user interface.
-Call Data from object and Used Es6

### CODE REVIEW

**Review by smunozmo — CHANGES_REQUESTED** [review]
Hi @olawalecoder, 👋  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that is not documented properly, please update your README file. Here's a [template](https://github.com/microverseinc/readme-template) you can use.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by olawalecoder** [comment]
> Hi @olawalecoder, 👋
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> * You have submitted a project, that is not documented properly, please update your README file. Here's a [template](https://github.com/microverseinc/readme-template) you can use.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> ✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> ⚠️ **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Sorry about that. I have updated it now

**Comment by smunozmo** [comment]
@olawalecoder great! Please submit a new code review once you are ready. 🚀

**Comment by olawalecoder** [comment]
> @olawalecoder great! Please submit a new code review once you are ready. 🚀

Yes, I have done that.

**Review by roshan-bajgain — APPROVED** [review]
# Approved 👏 

Hi @olawalecoder, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- There is no linter error at present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

- [ ] [Optional] You have added a README file, good job but when I check your live demo It was not working so kindly fix it 👍

**Pull request merged**
